version: '3'
services:
  mongo_db:
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=MeaDOaV2J9
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
